version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet build -c Release src/Dahomey.Cbor
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet test -c Release src/Dahomey.Cbor.Tests 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
